### ISSUE TITLE
Pyodide / Fetch Router

### ISSUE THREAD

**Issue by jiwnchoi** [jiwnchoi/Swipytics#24]
pyodide와 fetch가 같은 함수를 부르고 있는데 호출 방식이 달라서 불편함

중간에 라우터를 두는 것이 좋겠음 

라우터는 현재 routing target이 pyodide면 callPythonFunction을 실행하고 server면 fetch를 실행하는 함수.

- [ ] usePyodide 훅으로 Pyodide가 available인지 확인하는 로직이 있는데 싹 드러내고 useRouter 같은 것으로 변경
- [ ] useSetting 훅에 현재 라우터를 변경하는 부분이 있는데 router에 통합
- [ ] 서버 연결 확인 되면 자동으로 서버로 세팅하고 안되면 pyodide로 설정
- [ ] 라우터 모듈 인터페이스를 만들어서 hook이나 store 같은 상위 레이어에서는 같은 호출로 쓸 수 있도록 (pyodide인지 fetch인지를 모르고 실행할 수 있도록)

**Comment by SeojinSeojin** [comment]
### 설계

**`useRouter` 훅에서 리턴하는 것**
- `api` : 함수들 호출할 수 있는 인터페이스. 
  - 예를 들어 바깥에서 `api.browseCharts()` 호출하면 python이 "server"이면 fetch, "pyodide"이면 pyodide 호출한다. 
  - 타입은 pyodide function 정의할 때 썼던 걸 잘 재탕해본다.. 
  - 단점은 훅을 쓸 수 있는 곳에서만 api를 호출할 수 있다는 것 .. 그러나 이것은 기존에도 그러하였다
- `isLoading` : api를 쓸 수 있는 상태인지 리턴. 
  - pyodide면 pyodide가 다 로드되었는지 여부 리턴, server이면 "/api"에서 리스폰스 받았는지 리턴

**`useRouter`에서 하는 일**
- python이라는 값은 SettingsStore에서 갖고옴 
- python이 무엇이던 일단 pyodide를 로드해 둠
- 서버 연결 확인 되면 자동으로 서버로 세팅하고 안되면 pyodide로 설정

### 할 일
- [ ] 위와 같이 구현한다
- [ ] 중복되는 동작하는 기존 코드가 있다면 지우고 원래 호출되던 자리에 대체한다.
- [ ] 잘 작동하는지 확인한다

**Comment by jiwnchoi** [comment]
라우터가 훅이면 안되지 않나?

loadData 같은 것은 zustand setter에서 호출되잖어

**Comment by jiwnchoi** [comment]
사실 진작에 store에 데이터를 처리해서 적재하는 부분을 hook에서 받아다가 넣는 구조로 짜야했을 것 같은데 빨리 짜다보니 지금의 구조가 되어버렸,,,

내 생각에는 구조를 다 뜯어서 store에서 백엔드 호출을 하지 않게 바꾸거나

아니면 router를 독립된 클래스로 만들어서 약간 axios instance 처럼 사용할 수 있으면 좋을 것 같아 hook이나 store가 참조할 수 있고 worker를 참조하는 독립된 하위 계층으로으로

**Comment by SeojinSeojin** [comment]
그럼 라우터는 싱글톤 패턴의 객체로 구현하고, 

`router` 객체에서 리턴하는 것

- api : 함수들 호출할 수 있는 인터페이스.
- isLoading : api를 쓸 수 있는 상태인지 리턴.
- python : 'pyodide' | 'server', useSettingStore에 있는것 그대로 갖고오기
- setPython : useSettingStore에 있는것 그대로 갖고오기

`router` 객체가 하는 일
- python이 무엇이던 일단 pyodide를 로드해 둠
- 서버 연결 확인 되면 자동으로 서버로 세팅하고 안되면 pyodide로 설정

**Comment by jiwnchoi** [comment]
넹 좋은 것 같아요 일단 글케 해봅시다

**Comment by SeojinSeojin** [comment]
그래도 막 혹시나 store를 초기화하는 부분 등에서 백엔드 호출할 일이 있을 경우엔 useRouter보단 router가 쓰기 좋을 것 같아여

넹 일단 일케 해볼게욤

**Comment by jiwnchoi** [comment]
뜬금 없지만 

![image](https://github.com/user-attachments/assets/3f80a08c-6489-4f36-b8f8-f81608915464)

알게 모르게 boolean property에 대해 is를 안쓰는 컨벤션을 따르고 있숩니다 isLoading 말고 loading 뭐 이런 식으로...

깃허브 보다가 생각나서,,,참고,,,
