### ISSUE TITLE
Manual Exploration (Browse Tab)

### ISSUE THREAD

**Issue by jiwnchoi** [jiwnchoi/Swipytics#4]
## Manual Query (Gallery) of Visualization

Since swipe interaction only relies on the recommendation engine, it disables the user from directly choosing the exploration directions. 

We must design efficient interactions to facilitate the manual selection of exploration direction and recommendation algorithms. 

### Browse Chart

- [ ] Parse user input (Parse field names from user input) 
- [ ] Show browsed charts (/api/browseChart)

---

사용자 입력을 파싱하는 처리하는 로직은 그 LinkedIn이나 Workadays같은 사이트에 보면 기술 스택 입력하는 메타포를 따라가려고 함. 

인풋 창이 있어서 입력하면 자동 완성 가능한 필드들이 뜨고 터치하면 추가되고,,, 느낌 아니까,,,,

Browsed Chart를 보여주는 것은 Bookmark 처럼 리스트로 보여주어야 할듯?

**Comment by SeojinSeojin** [comment]
fields와 입력값 비교할 라이브러리

https://www.fusejs.io/getting-started/installation.html
